# This file was generated by GoReleaser. DO NOT EDIT.
cask "buffers" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "1d3f29f9d862d0dc70e69f9008b57bedd327cb3b8928d66b1e126a6f592f9394"
      url "https://github.com/the-protobuf-project/buffers/releases/download/v#{version}/buffers_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/buffers/"
    end
    on_intel do
      sha256 "36dc9ae7fb45ac473be5ea637d4bb4c3d6a5be8a7440b9f4426a046fbd78be11"
      url "https://github.com/the-protobuf-project/buffers/releases/download/v#{version}/buffers_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/buffers/"
    end
  end
  on_linux do
    on_arm do
      sha256 "a520b379b06c62cf35bfbcb944d76519ca94447ecbd7aab06781b78042e11a7b"
      url "https://github.com/the-protobuf-project/buffers/releases/download/v#{version}/buffers_#{version}_linux_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/buffers/"
    end
    on_intel do
      sha256 "6cda263c0635b48540b2f283282cfaa51330b6a373eb0661d93cdfac6aebbd1b"
      url "https://github.com/the-protobuf-project/buffers/releases/download/v#{version}/buffers_#{version}_linux_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/buffers/"
    end
  end

  name "buffers"
  desc "Generate FlatBuffers, Cap n Proto, ROS and Wire schema from AIP-annotated protobuf"
  homepage "https://github.com/the-protobuf-project/buffers"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-buffers"
  binary "buffers"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-buffers"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/buffers"]
    end
  end

  # No zap stanza required
end
