# This file was generated by GoReleaser. DO NOT EDIT.
cask "buffers" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "fdbf8ec151714ec0bf0e80033550928911c18df56892e5924781499ab08a3689"
      url "https://github.com/the-protobuf-project/buffers/releases/download/v#{version}/buffers_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/buffers/"
    end
    on_intel do
      sha256 "8f2e9b749e4d24c5a577747a0f3067aa8b69711ebb5d9e9ac92acbe6b2a892c2"
      url "https://github.com/the-protobuf-project/buffers/releases/download/v#{version}/buffers_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/buffers/"
    end
  end
  on_linux do
    on_arm do
      sha256 "2f4902564cf121d289975b278ae94413fe820856c9ec084792fe6976c2d3780c"
      url "https://github.com/the-protobuf-project/buffers/releases/download/v#{version}/buffers_#{version}_linux_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/buffers/"
    end
    on_intel do
      sha256 "c286f6bf16f3bab1b445fa9abac11d45a33637dc40d084a60c60f305c3296ec0"
      url "https://github.com/the-protobuf-project/buffers/releases/download/v#{version}/buffers_#{version}_linux_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/buffers/"
    end
  end

  name "buffers"
  desc "Generate FlatBuffers, Cap n Proto, ROS and Wire schema from AIP-annotated protobuf"
  homepage "https://github.com/the-protobuf-project/buffers"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-buffers"
  binary "buffers"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-buffers"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/buffers"]
    end
  end

  # No zap stanza required
end
