# This file was generated by GoReleaser. DO NOT EDIT.
cask "buffers" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "70d9e0c333a031927a78f8dceeb99b916937ad068227fab5bb0dab58fc1b9c25"
      url "https://github.com/the-protobuf-project/buffers/releases/download/v#{version}/buffers_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/buffers/"
    end
    on_intel do
      sha256 "f85fd300ef39dc963110397a0e718ec537ff1e37e0206fea64c61cf2d246dd4e"
      url "https://github.com/the-protobuf-project/buffers/releases/download/v#{version}/buffers_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/buffers/"
    end
  end
  on_linux do
    on_arm do
      sha256 "6164c6a517349ccd5bcd6de28c2e01e4e0c6b619a0a8042721a12c07247a3f1a"
      url "https://github.com/the-protobuf-project/buffers/releases/download/v#{version}/buffers_#{version}_linux_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/buffers/"
    end
    on_intel do
      sha256 "0c4ed2858dc68843bb23993af9b3cb33e113a813f2990b67958f697a31e273ce"
      url "https://github.com/the-protobuf-project/buffers/releases/download/v#{version}/buffers_#{version}_linux_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/buffers/"
    end
  end

  name "buffers"
  desc "Generate FlatBuffers, Cap n Proto, ROS and Wire schema from AIP-annotated protobuf"
  homepage "https://github.com/the-protobuf-project/buffers"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-buffers"
  binary "buffers"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-buffers"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/buffers"]
    end
  end

  # No zap stanza required
end
