# This file was generated by GoReleaser. DO NOT EDIT.
cask "gnostic" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "fa164b691acd276b6de02c93aee57aab075768d06475deee5ddddb683a3f06e6"
      url "https://github.com/the-protobuf-project/gnostic/releases/download/v#{version}/gnostic_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0976af807c98b7392bb1a7d28df5a9e5d8becf530ee2e9d0804b92cb0aef16ff"
      url "https://github.com/the-protobuf-project/gnostic/releases/download/v#{version}/gnostic_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5348b3d98b8044fbee4a0e32ee2a196460735a1f6e40ba7d958a1df1d7d61d89"
      url "https://github.com/the-protobuf-project/gnostic/releases/download/v#{version}/gnostic_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0fc1b7601b21ead554990b3e79ca92f1443aa6d8b306cdc66e0a9c68ca8b0d3a"
      url "https://github.com/the-protobuf-project/gnostic/releases/download/v#{version}/gnostic_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gnostic"
  desc "Tool for building better REST APIs through knowledge; converts OpenAPI to/from Protocol Buffers and generates OpenAPI/JSON Schema from .proto files"
  homepage "https://github.com/the-protobuf-project/gnostic"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gnostic"
  binary "protoc-gen-openapi"
  binary "protoc-gen-jsonschema"

  postflight do
    if OS.mac?
      ["gnostic", "protoc-gen-openapi", "protoc-gen-jsonschema"].each do |b|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{b}"]
      end
    end
  end

  # No zap stanza required

end
