# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-openapi-solo" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "0d56ca1e8fbe296f395fc5e38b6b5ecb2ec34c94046847bf076fd0fff62c7e2f"
      url "https://github.com/the-protobuf-project/protoc-gen-openapi-solo/releases/download/v#{version}/protoc-gen-openapi_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f91c2c14e5b12fc95353d32649a93e557f6371abc8f70383cf49c93d9180a6b1"
      url "https://github.com/the-protobuf-project/protoc-gen-openapi-solo/releases/download/v#{version}/protoc-gen-openapi_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "539001004850b929391ff2a38ab1c9571f7f1d3e67a77aa240eff34e80a01619"
      url "https://github.com/the-protobuf-project/protoc-gen-openapi-solo/releases/download/v#{version}/protoc-gen-openapi_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "01861fe0cd8d3a4997bdd4cc691b1a9e26b22502d544f4ada8440b7ec92c073b"
      url "https://github.com/the-protobuf-project/protoc-gen-openapi-solo/releases/download/v#{version}/protoc-gen-openapi_#{version}_linux_arm64.tar.gz"
    end
  end

  name "protoc-gen-openapi-solo"
  desc "protoc plugin that generates OpenAPI v3 specs from protobuf definitions"
  homepage "https://github.com/the-protobuf-project/protoc-gen-openapi-solo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-openapi", target: "protoc-gen-openapi-solo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-openapi"]
    end
  end

  # No zap stanza required

end
