# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-protorm" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "2a6df825d7b27955f72ba18e33a7f47490d5c01aafe321910b97771d6160cb17"
      url "https://github.com/the-protobuf-project/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/protorm/"
    end
    on_arm do
      sha256 "0d81d83fb9695f024f70fa9318bd41c88d596c5d7c1739bae7b512dfe7f52810"
      url "https://github.com/the-protobuf-project/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/protorm/"
    end
  end

  on_linux do
    on_intel do
      sha256 "1bd4928da1c271105336bc77325c808a721ee6b0cfe50e407849987ca0b94880"
      url "https://github.com/the-protobuf-project/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/protorm/"
    end
    on_arm do
      sha256 "a5cee811f86bc9ca15b7b8dd541568c3e856c793aa6e8f07207734449a719134"
      url "https://github.com/the-protobuf-project/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/protorm/"
    end
  end

  name "protoc-gen-protorm"
  desc "Protoc plugin generating Prisma, GORM, SQL & CSV schemas from Protobuf + AIP annotations"
  homepage "https://github.com/the-protobuf-project/protorm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-protorm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-protorm"]
    end
  end

  # No zap stanza required

end
