# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-protorm" do
  version "0.1.61"

  on_macos do
    on_intel do
      sha256 "038e650be79ea351c84fbe6b5b42b63c7c5d08576a6bec96b01eacbf538fda59"
      url "https://github.com/the-protobuf-project/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/protorm/"
    end
    on_arm do
      sha256 "346df4ad2191e5f421e7914e5c8b0185b81e9e628d42595c14076d5ad0dd1e9f"
      url "https://github.com/the-protobuf-project/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/protorm/"
    end
  end

  on_linux do
    on_intel do
      sha256 "6798197ff1c31701f55ab4b7361b1d1d41579339674012617d044e4e6c002425"
      url "https://github.com/the-protobuf-project/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/protorm/"
    end
    on_arm do
      sha256 "79c008d47ca06073c27b9a31358aa865e0feb4d8aaa32d6486f9a3ac5c42612b"
      url "https://github.com/the-protobuf-project/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/protorm/"
    end
  end

  name "protoc-gen-protorm"
  desc "Protoc plugin generating Prisma, GORM, SQL & CSV schemas from Protobuf + AIP annotations"
  homepage "https://github.com/the-protobuf-project/protorm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-protorm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-protorm"]
    end
  end

  # No zap stanza required

end
