# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-store" do
  version "1.5.1"

  on_macos do
    on_intel do
      sha256 "91bc0e042728e4cf18506406c7649360da49ade68f66ef0c23949333f9964999"
      url "https://github.com/the-protobuf-project/store/releases/download/v#{version}/protoc-gen-store_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/store/"
    end
    on_arm do
      sha256 "7e483277f3917e0670dc1515f1a7ac8bfd88bd10adef5d0ad2563d4417367be4"
      url "https://github.com/the-protobuf-project/store/releases/download/v#{version}/protoc-gen-store_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/store/"
    end
  end

  on_linux do
    on_intel do
      sha256 "6b297d3cc227bb008710c18d16a6b453c253befc9dac7dfbfeac5aa38faec8ec"
      url "https://github.com/the-protobuf-project/store/releases/download/v#{version}/protoc-gen-store_#{version}_linux_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/store/"
    end
    on_arm do
      sha256 "0fbf98d2d1463b00352666d72a146f4cd1e43a2fcf134fc778ae82b6f42da7fb"
      url "https://github.com/the-protobuf-project/store/releases/download/v#{version}/protoc-gen-store_#{version}_linux_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/store/"
    end
  end

  name "protoc-gen-store"
  desc "Protoc plugin generating Prisma, GORM & SQL schemas from Protobuf + AIP annotations"
  homepage "https://github.com/the-protobuf-project/store"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-store"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-store"]
    end
  end

  # No zap stanza required

end
