# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-mcp" do
  version "1.7.3"

  on_macos do
    on_arm do
      sha256 "5c147528e1c550bc6b328511883b26437063e85ede5450f36e270202366ed79a"
      url "https://github.com/the-protobuf-project/mcp/releases/download/v#{version}/protoc-gen-mcp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "263f4391654b0657be00a0a79fbe118e3f0e022ef66cfe241effa3e943e5bc0a"
      url "https://github.com/the-protobuf-project/mcp/releases/download/v#{version}/protoc-gen-mcp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3892dcaacc2f004e9cba599e2f56fbd3992c346dee5ad4453dedfef5cb685afc"
      url "https://github.com/the-protobuf-project/mcp/releases/download/v#{version}/protoc-gen-mcp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "28f8bfd9e8954da5f4cacd9654456a6c26e8156b06f9dd8e6416e6ee84df1d09"
      url "https://github.com/the-protobuf-project/mcp/releases/download/v#{version}/protoc-gen-mcp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "protoc-gen-mcp"
  desc "Protoc plugin generating MCP server code (Go, Rust, C++) from Protobuf + gRPC definitions"
  homepage "https://github.com/the-protobuf-project/mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-mcp"]
    end
  end

  # No zap stanza required
end
