# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-protorm" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "2c80af797649be4f939968c957fcaa8cf92a5d375af46b8ecd1226b78ac38352"
      url "https://github.com/the-protobuf-project/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/protorm/"
    end
    on_arm do
      sha256 "527f50071cce3a0fae127085c9700c5804e15405eacbafbef5446f9088794282"
      url "https://github.com/the-protobuf-project/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/protorm/"
    end
  end

  on_linux do
    on_intel do
      sha256 "62bd27244d9c3005e6f2fac00d0ffbb4cc10151d7854b073ec9445e662b4d8ef"
      url "https://github.com/the-protobuf-project/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/protorm/"
    end
    on_arm do
      sha256 "b69a48a6f1070a77188f2a9396a3a9941a53f830cf8ec2141c69b5fed1c3f0f2"
      url "https://github.com/the-protobuf-project/protorm/releases/download/v#{version}/protoc-gen-protorm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/protorm/"
    end
  end

  name "protoc-gen-protorm"
  desc "Protoc plugin generating Prisma, GORM, SQL & CSV schemas from Protobuf + AIP annotations"
  homepage "https://github.com/the-protobuf-project/protorm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-protorm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-protorm"]
    end
  end

  # No zap stanza required

end
