# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-openapi-solo" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "dd51b60ae64436b52600302c0c6367392a2fd8194babb0bdf190145325a11efa"
      url "https://github.com/the-protobuf-project/protoc-gen-openapi-solo/releases/download/v#{version}/protoc-gen-openapi_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d77b6bb9b67db2b52b1224fe639dba07659232ad20e3cf0b7f68964c4f5b7b8d"
      url "https://github.com/the-protobuf-project/protoc-gen-openapi-solo/releases/download/v#{version}/protoc-gen-openapi_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "66ff451b0a8d521774feef005c159ea95926d9f3aeddf198ce7139dfe59acd29"
      url "https://github.com/the-protobuf-project/protoc-gen-openapi-solo/releases/download/v#{version}/protoc-gen-openapi_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ed1247685c1c6fa04caafb3483d65fd2511903c91adc279251ae1e51b173c24d"
      url "https://github.com/the-protobuf-project/protoc-gen-openapi-solo/releases/download/v#{version}/protoc-gen-openapi_#{version}_linux_arm64.tar.gz"
    end
  end

  name "protoc-gen-openapi-solo"
  desc "protoc plugin that generates OpenAPI v3 specs from protobuf definitions"
  homepage "https://github.com/the-protobuf-project/protoc-gen-openapi-solo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-openapi-solo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-openapi"]
    end
  end

  # No zap stanza required

end
