# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-store" do
  version "1.5.3"

  on_macos do
    on_arm do
      sha256 "307f64f71ace3e9cecfa58046fcb7162279cd50cda3983dc2d734a936711dd99"
      url "https://github.com/the-protobuf-project/store/releases/download/v#{version}/protoc-gen-store_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0bb262351c3a0bfe65ab009964697047021f632940f8a0a3ecb186c0483633f1"
      url "https://github.com/the-protobuf-project/store/releases/download/v#{version}/protoc-gen-store_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8107c435bf277810f2c1f008cc2e4468e6472351af6c1fb879a0334dfbec3357"
      url "https://github.com/the-protobuf-project/store/releases/download/v#{version}/protoc-gen-store_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1fcccbfea5e03bd9d729d2c04b85631e75f55166704843e3ef7e3f1d732282c0"
      url "https://github.com/the-protobuf-project/store/releases/download/v#{version}/protoc-gen-store_#{version}_linux_amd64.tar.gz"
    end
  end

  name "protoc-gen-store"
  desc "Protoc plugin generating Prisma, GORM & SQL schemas from Protobuf + AIP annotations"
  homepage "https://github.com/the-protobuf-project/store"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-store"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-store"]
    end
  end

  # No zap stanza required
end
