# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-orm" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "ad37383f6f549bf05c124491c51b813555e15332c9192a7bf135273293b49877"
      url "https://github.com/the-protobuf-project/orm/releases/download/v#{version}/protoc-gen-orm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/orm/"
    end
    on_arm do
      sha256 "53fdb8c5c87a58c88aeec75952976c223be4dfa0c31c76849517bb722d38a679"
      url "https://github.com/the-protobuf-project/orm/releases/download/v#{version}/protoc-gen-orm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/orm/"
    end
  end

  on_linux do
    on_intel do
      sha256 "5b5f92cefee8e059deb6c2a62de14f2c2e2f81e1fff5dae733e088ff015c8fa5"
      url "https://github.com/the-protobuf-project/orm/releases/download/v#{version}/protoc-gen-orm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/orm/"
    end
    on_arm do
      sha256 "cd8069037c8486353e324906cff5a8c8afec6b1daa55b811e359d784f207a863"
      url "https://github.com/the-protobuf-project/orm/releases/download/v#{version}/protoc-gen-orm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/orm/"
    end
  end

  name "protoc-gen-orm"
  desc "Protoc plugin generating Prisma, GORM & SQL schemas from Protobuf + AIP annotations"
  homepage "https://github.com/the-protobuf-project/orm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-orm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-orm"]
    end
  end

  # No zap stanza required

end
