# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-mcp" do
  version "1.6.1"

  on_macos do
    on_intel do
      sha256 "a2cedca2dd3dcfda74495d8f3352832b78eee44faec0371fee8b32f6bf393218"
      url "https://github.com/the-protobuf-project/grpc-mcp-gateway/releases/download/v#{version}/protoc-gen-mcp_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/grpc-mcp-gateway/"
    end
    on_arm do
      sha256 "e8c7694946423dc26c89e7363587b2d205cbf2f637256eec33bebb5033b0e210"
      url "https://github.com/the-protobuf-project/grpc-mcp-gateway/releases/download/v#{version}/protoc-gen-mcp_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/grpc-mcp-gateway/"
    end
  end

  on_linux do
    on_intel do
      sha256 "fc06c10bfa260715f5a06c8c339e7192052a0bcea2494f69e334e5a13512907b"
      url "https://github.com/the-protobuf-project/grpc-mcp-gateway/releases/download/v#{version}/protoc-gen-mcp_#{version}_linux_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/grpc-mcp-gateway/"
    end
    on_arm do
      sha256 "6ecee52e202cbcb568f7c06e8a8cdfa04183d7fe0d67402a3e923213aaa57310"
      url "https://github.com/the-protobuf-project/grpc-mcp-gateway/releases/download/v#{version}/protoc-gen-mcp_#{version}_linux_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/grpc-mcp-gateway/"
    end
  end

  name "protoc-gen-mcp"
  desc "Protoc plugin generating MCP server code (Go, Python, Rust, C++) from Protobuf + gRPC definitions"
  homepage "https://github.com/the-protobuf-project/grpc-mcp-gateway"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-mcp"]
    end
  end

  # No zap stanza required

end
