# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-orm" do
  version "1.2.01"

  on_macos do
    on_intel do
      sha256 "729b98f62389caacbc8e087adad4bd43c4a973fa5c54fb8e88df3c6ff34ca0f0"
      url "https://github.com/the-protobuf-project/orm/releases/download/v#{version}/protoc-gen-orm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/orm/"
    end
    on_arm do
      sha256 "0f5c986e7e93aecc55a1ea240a9e970e754b586dc3d0f8dce594dbe18f365c59"
      url "https://github.com/the-protobuf-project/orm/releases/download/v#{version}/protoc-gen-orm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/orm/"
    end
  end

  on_linux do
    on_intel do
      sha256 "84928cbbd54316b60b5b407e43c2e98b9cd82b6f63248699a7d5344f109aac25"
      url "https://github.com/the-protobuf-project/orm/releases/download/v#{version}/protoc-gen-orm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/orm/"
    end
    on_arm do
      sha256 "e5362e1440342d8f49618a852744f6b669b3ddd9e87d5dae0ef77cb7793f9b21"
      url "https://github.com/the-protobuf-project/orm/releases/download/v#{version}/protoc-gen-orm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/orm/"
    end
  end

  name "protoc-gen-orm"
  desc "Protoc plugin generating Prisma, GORM & SQL schemas from Protobuf + AIP annotations"
  homepage "https://github.com/the-protobuf-project/orm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-orm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-orm"]
    end
  end

  # No zap stanza required

end
