# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-orm" do
  version "1.4.2"

  on_macos do
    on_intel do
      sha256 "73a5c966a8c275026f76797da422d4dac4d263eb77a279db1e1f2d65f38e5f70"
      url "https://github.com/the-protobuf-project/orm/releases/download/v#{version}/protoc-gen-orm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/orm/"
    end
    on_arm do
      sha256 "d075be8ebdd8ca927a6949baaa95989c8f08a00622252a9f9ea01af662a2acfe"
      url "https://github.com/the-protobuf-project/orm/releases/download/v#{version}/protoc-gen-orm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/orm/"
    end
  end

  on_linux do
    on_intel do
      sha256 "7241d751c39da38aca4c150e75f0bdd71d775db72f647b53eee732f9562649d3"
      url "https://github.com/the-protobuf-project/orm/releases/download/v#{version}/protoc-gen-orm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/orm/"
    end
    on_arm do
      sha256 "a3df7565a625d4c11f01c2c6c0aceb9da8f665c703cc05df169c47886a38b8eb"
      url "https://github.com/the-protobuf-project/orm/releases/download/v#{version}/protoc-gen-orm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/orm/"
    end
  end

  name "protoc-gen-orm"
  desc "Protoc plugin generating Prisma, GORM & SQL schemas from Protobuf + AIP annotations"
  homepage "https://github.com/the-protobuf-project/orm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-orm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-orm"]
    end
  end

  # No zap stanza required

end
