# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-store" do
  version "1.5.2"

  on_macos do
    on_arm do
      sha256 "cc3c58a7869c4342742ae700097434d5afaa3ff89a7b38a81cf45d46fed495db"
      url "https://github.com/the-protobuf-project/store/releases/download/v#{version}/protoc-gen-store_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8ec8ba6e6caed200c961ded593a7973fe240a1a1f055a51737d4040cfb352eb1"
      url "https://github.com/the-protobuf-project/store/releases/download/v#{version}/protoc-gen-store_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9862a4ae798701d727a840ae5059d2d845048d441c6815ae10f28272790a1319"
      url "https://github.com/the-protobuf-project/store/releases/download/v#{version}/protoc-gen-store_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f2b9fc538e410fbb461e231a05020b0b69f16f8cb056cf8f3d1b2d9815889f07"
      url "https://github.com/the-protobuf-project/store/releases/download/v#{version}/protoc-gen-store_#{version}_linux_amd64.tar.gz"
    end
  end

  name "protoc-gen-store"
  desc "Protoc plugin generating Prisma, GORM & SQL schemas from Protobuf + AIP annotations"
  homepage "https://github.com/the-protobuf-project/store"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-store"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-store"]
    end
  end

  # No zap stanza required
end
