# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-mcp" do
  version "1.7.1"

  on_macos do
    on_intel do
      sha256 "2cd0aed5446eb2fc827262b2057d50200237973b53b6a8d3a237136744954e88"
      url "https://github.com/the-protobuf-project/mcp/releases/download/v#{version}/protoc-gen-mcp_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/mcp/"
    end
    on_arm do
      sha256 "5b825173ccf4c5e90298a8ef7da900d465aa9a6da0df924fb22759e721947490"
      url "https://github.com/the-protobuf-project/mcp/releases/download/v#{version}/protoc-gen-mcp_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/mcp/"
    end
  end

  on_linux do
    on_intel do
      sha256 "a59710cf3ee7fb84f05fa8822dbdc61d6b17acf0fa4a21486085a3205d3dba47"
      url "https://github.com/the-protobuf-project/mcp/releases/download/v#{version}/protoc-gen-mcp_#{version}_linux_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/mcp/"
    end
    on_arm do
      sha256 "835a345f698eab8e39b74a189a653ebd1f01d6dbb05f1c209e33e42e6603ce3c"
      url "https://github.com/the-protobuf-project/mcp/releases/download/v#{version}/protoc-gen-mcp_#{version}_linux_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/mcp/"
    end
  end

  name "protoc-gen-mcp"
  desc "Protoc plugin generating MCP server code (Go, Rust, C++) from Protobuf + gRPC definitions"
  homepage "https://github.com/the-protobuf-project/mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-mcp"]
    end
  end

  # No zap stanza required

end
