# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-cache" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "18c357e85ecbe35be54cf2f95df90c715f93d51aa8fd9c9b8e1b0f69f3acc73d"
      url "https://github.com/the-protobuf-project/cache/releases/download/v#{version}/protoc-gen-cache_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/cache/"
    end
    on_intel do
      sha256 "9461a98989fbb151390a487ed1b416d491e903cd35e0f613e81263aa288aa35d"
      url "https://github.com/the-protobuf-project/cache/releases/download/v#{version}/protoc-gen-cache_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/cache/"
    end
  end
  on_linux do
    on_arm do
      sha256 "b2ed8463b80b71bf1db5b9389e77b7c7e5bcfb90e1642e0a42d519360ebac1e9"
      url "https://github.com/the-protobuf-project/cache/releases/download/v#{version}/protoc-gen-cache_#{version}_linux_arm64.tar.gz",
        verified: "github.com/the-protobuf-project/cache/"
    end
    on_intel do
      sha256 "31accb626de9594b2b9731b98521a254d3b04b7dfdad49e8bce0cc0400f58d24"
      url "https://github.com/the-protobuf-project/cache/releases/download/v#{version}/protoc-gen-cache_#{version}_linux_amd64.tar.gz",
        verified: "github.com/the-protobuf-project/cache/"
    end
  end

  name "protoc-gen-cache"
  desc "Generate typed read-through cache decorators over protoc-gen-store stores"
  homepage "https://github.com/the-protobuf-project/cache"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-cache"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-cache"]
    end
  end

  # No zap stanza required
end
