# This file was generated by GoReleaser. DO NOT EDIT.
cask "protoc-gen-openapi-solo" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "b89fc4bf948c74828355d187d388afd94036a35cef9838c4695fce5e0cf81d18"
      url "https://github.com/the-protobuf-project/protoc-gen-openapi-solo/releases/download/v#{version}/protoc-gen-openapi_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "155567205961f14afc060ca3fd2a58a7d982e7b4650985cd1065b780f1148ac5"
      url "https://github.com/the-protobuf-project/protoc-gen-openapi-solo/releases/download/v#{version}/protoc-gen-openapi_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c3d9ed9b3e095038f31ab1f3303d7a263a53949ecf3e3059c93d3eebe3d91e8c"
      url "https://github.com/the-protobuf-project/protoc-gen-openapi-solo/releases/download/v#{version}/protoc-gen-openapi_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "80b79429e277e59f2dce2f18ebce605e3360232062e514524ded61ef749bc7ee"
      url "https://github.com/the-protobuf-project/protoc-gen-openapi-solo/releases/download/v#{version}/protoc-gen-openapi_#{version}_linux_arm64.tar.gz"
    end
  end

  name "protoc-gen-openapi-solo"
  desc "protoc plugin that generates OpenAPI v3 specs from protobuf definitions"
  homepage "https://github.com/the-protobuf-project/protoc-gen-openapi-solo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "protoc-gen-openapi-solo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/protoc-gen-openapi-solo"]
    end
  end

  # No zap stanza required

end
