# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Buffman < Formula
  desc "CLI tool that wraps flatc to convert .proto files to .fbs and generate multi-language code from a declarative YAML config"
  homepage "https://github.com/the-protobuf-project/buffman"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/the-protobuf-project/buffman/releases/download/v0.1.0/buffman_0.1.0_darwin_amd64.tar.gz"
      sha256 "ce5797f22f660373f1880046888f0a8f16aa5b1391943a710f2ac11c9b360f4f"

      define_method(:install) do
        bin.install "buffman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/the-protobuf-project/buffman/releases/download/v0.1.0/buffman_0.1.0_darwin_arm64.tar.gz"
      sha256 "9ac990ba8e9e33b47e52e7d0eb13b2140c0e1b1bba473f5911cfe411a8293a75"

      define_method(:install) do
        bin.install "buffman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/the-protobuf-project/buffman/releases/download/v0.1.0/buffman_0.1.0_linux_amd64.tar.gz"
      sha256 "64e54e1f2a064e6662eded51a3cd17a59d2b424f50b08b44107da9746b99caa0"
      define_method(:install) do
        bin.install "buffman"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/the-protobuf-project/buffman/releases/download/v0.1.0/buffman_0.1.0_linux_arm64.tar.gz"
      sha256 "ffd0d6e256ab74afa9a27e921b913f7d1aa3d09c9fd09923bc687d408f7ad063"
      define_method(:install) do
        bin.install "buffman"
      end
    end
  end

  test do
    system "#{bin}/buffman", "--help"
  end
end
