# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Buffman < Formula
  desc "CLI tool that wraps flatc to convert .proto files to .fbs and generate multi-language code from a declarative YAML config"
  homepage "https://github.com/the-protobuf-project/buffman"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/the-protobuf-project/buffman/releases/download/v0.1.0/buffman_0.1.0_darwin_amd64.tar.gz"
      sha256 "8b58919cd801f5572f9309aa8474b4ba2219c0b51389007c4d2f813f78cc166d"

      define_method(:install) do
        bin.install "buffman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/the-protobuf-project/buffman/releases/download/v0.1.0/buffman_0.1.0_darwin_arm64.tar.gz"
      sha256 "73a93782a5a9edc1fa534362eb8f062c25b529d5f82e7cef986b25bec63e593e"

      define_method(:install) do
        bin.install "buffman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/the-protobuf-project/buffman/releases/download/v0.1.0/buffman_0.1.0_linux_amd64.tar.gz"
      sha256 "e42d7452f4bd9c28e6bf94ab78301658c47d979e79230d96364a52c33c4f6694"
      define_method(:install) do
        bin.install "buffman"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/the-protobuf-project/buffman/releases/download/v0.1.0/buffman_0.1.0_linux_arm64.tar.gz"
      sha256 "7ea5ca7737188d95367edcdfcba5d466c884cb9bbf5a1a09092cfdcd1db5ec7b"
      define_method(:install) do
        bin.install "buffman"
      end
    end
  end

  test do
    system "#{bin}/buffman", "--help"
  end
end
