# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocGenGoGapic < Formula
  desc "GAPIC protoc plugin for Go (protoc-gen-go_gapic), redistributed from googleapis/gapic-generator-go"
  homepage "https://github.com/the-protobuf-project/gapic"
  version "0.62.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/the-protobuf-project/gapic/releases/download/go-v0.62.0/protoc-gen-go_gapic_0.62.0_darwin_amd64.tar.gz"
      sha256 "a3109bfe74230e07719bcb5497a088b8bc0a558cd55129ceaf5eae842ba6027f"

      define_method(:install) do
        bin.install "protoc-gen-go_gapic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/the-protobuf-project/gapic/releases/download/go-v0.62.0/protoc-gen-go_gapic_0.62.0_darwin_arm64.tar.gz"
      sha256 "fb6ae0f8e6e58f4b5d86266c4f497b49a955f16b37ea5d956706df354f00dd37"

      define_method(:install) do
        bin.install "protoc-gen-go_gapic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/the-protobuf-project/gapic/releases/download/go-v0.62.0/protoc-gen-go_gapic_0.62.0_linux_amd64.tar.gz"
      sha256 "fa28df093a6c0cae992fa75216b4fd724d264a0f7a9a9d99f64ea891f5128ca2"
      define_method(:install) do
        bin.install "protoc-gen-go_gapic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/the-protobuf-project/gapic/releases/download/go-v0.62.0/protoc-gen-go_gapic_0.62.0_linux_arm64.tar.gz"
      sha256 "6bdb6fe954d9e1f05b869e7cf711d9db76faf4db970a2e7bc31c27efd6f2cae0"
      define_method(:install) do
        bin.install "protoc-gen-go_gapic"
      end
    end
  end

  test do
    assert_predicate bin/"protoc-gen-go_gapic", :executable?
  end
end
