# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocGenGoGapic < Formula
  desc "GAPIC protoc plugin for Go (protoc-gen-go_gapic), redistributed from googleapis/gapic-generator-go"
  homepage "https://github.com/the-protobuf-project/gapic"
  version "0.63.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/the-protobuf-project/gapic/releases/download/go-v0.63.0/protoc-gen-go_gapic_0.63.0_darwin_amd64.tar.gz"
      sha256 "02c22433a635688e97ecfe7899fdc5e793fc7eeb24803fab97494a5c7337745e"

      define_method(:install) do
        bin.install "protoc-gen-go_gapic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/the-protobuf-project/gapic/releases/download/go-v0.63.0/protoc-gen-go_gapic_0.63.0_darwin_arm64.tar.gz"
      sha256 "01d8584090fd639c75d8ff5e8a890ea3bd42b60e4e922f3be4a71f8bd5a3b249"

      define_method(:install) do
        bin.install "protoc-gen-go_gapic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/the-protobuf-project/gapic/releases/download/go-v0.63.0/protoc-gen-go_gapic_0.63.0_linux_amd64.tar.gz"
      sha256 "43547f0a3caf293229e3c5bf59d98e8d55fbebe6700e69f88ce088861eb63d3a"
      define_method(:install) do
        bin.install "protoc-gen-go_gapic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/the-protobuf-project/gapic/releases/download/go-v0.63.0/protoc-gen-go_gapic_0.63.0_linux_arm64.tar.gz"
      sha256 "7c588f9ef4fcb142ec9d95b052d72d6523c42835ea48c6e5737a63e28d8bbc57"
      define_method(:install) do
        bin.install "protoc-gen-go_gapic"
      end
    end
  end

  test do
    assert_predicate bin/"protoc-gen-go_gapic", :executable?
  end
end
